section/urls.py
from . import views
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.log_out, name='logout'),
    url(r'^signup$', views.sign_up, name='signup'),
    url(r'^all$', views.all_sections, name='all_sections'),
    url(r'^register$', views.register, name='register'),
    url(r'^$', views.sections, name='sections'),
]

sections/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sections/', include('section.urls', namespace='section')),
    url(r'^$', views.to_main)
]

section/models.py
from __future__ import unicode_literals

from django.db import models


class Student(models.Model):
    sid = models.IntegerField()
    name = models.CharField(max_length=255)
    password = models.CharField(max_length=255)

    def __str__(self):
        return self.name + ": " + str(self.sid)

    def __unicode__(self):
        return self.name + ": " + str(self.sid)


class Course(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name


class Section(models.Model):
    date = models.CharField(max_length=255)
    capacity = models.IntegerField(default=25)
    place = models.CharField(max_length=255)
    course = models.ForeignKey('Course', on_delete=models.CASCADE)
    students = models.ManyToManyField(Student)

    def __str__(self):
        return self.date + " - " + self.place

    def __unicode__(self):
        return self.date + " - " + self.place

section/forms.py
from django import forms
from django.core import validators


class login_form(forms.Form):
    id = forms.IntegerField()
    password = forms.CharField(max_length=255)


class sign_up_form(forms.Form):
    id = forms.IntegerField()
    name = forms.CharField(max_length=255)
    password = forms.CharField(max_length=255)
    password2 = forms.CharField(max_length=255)

section/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from section import forms
from section.models import Section, Student


def login(request):
    if request.method == 'POST':
        form = forms.login_form(request.POST)
        if form.is_valid():
            student_id = form.cleaned_data['id']
            password = form.cleaned_data['password']
            students = Student.objects.filter(sid=student_id)
            if len(students) > 0 and password == students[0].password:
                request.session['sid'] = student_id
            else:
                return render(request, "section/login.html", {'form': form})
            return redirect('/sections/')
        else:
            return render(request, "section/login.html", {'form': form})
    form = forms.login_form()
    return render(request, "section/login.html", {'form': form})


def sign_up(request):
    if request.method == 'POST':
        form = forms.sign_up_form(request.POST)
        if form.is_valid():
            student_id = form.cleaned_data['id']
            name = form.cleaned_data['name']
            password = form.cleaned_data['password']
            password2 = form.cleaned_data['password2']
            if password == password2:
                new_student = Student()
                new_student.name = name
                new_student.sid = student_id
                new_student.password = password
                new_student.save()
                return redirect('/sections/login')

    form = forms.sign_up_form()
    return render(request, "section/signup.html", {'form': form})


def sections(request):
    sid = request.session.get('sid')
    if sid is None:
        return redirect('/sections/login')
    else:
        student = Student.objects.get(sid=sid)
        sections = student.section_set.all()
        sections_list = []
        names_set = set()
        for section in sections:
            sections_list.append((section.date, section.course.name))
            names_set.add(section.course.name)
        return render(request, 'section/sections.html', {'sections': sections_list, 'names': names_set})


def all_sections(request):
    sections = Section.objects.all()
    sections_list = []
    names_set = set()
    for section in sections:
        sections_list.append((section.date, section.course.name, section.id))
        names_set.add(section.course.name)
    return render(request, 'section/all_sections.html', {'sections': sections_list, 'names': names_set})


def register(request):
    if request.method == 'GET':
        student_sid = request.session.get('sid')
        if student_sid is None:
            student_sid = request.GET.get('sid')
            if student_sid is None:
                return JsonResponse({'success': False, 'message': 'wrong parameters: student sid is missing'})

        section_id = request.GET.get('id')
        if section_id is None:
            return JsonResponse({'success': False, 'message': 'wrong parameters: section id is missing'})

        student = Student.objects.get(sid=student_sid)
        section = Section.objects.get(pk=section_id)

        for s in student.section_set.all():
            if s.course.id == section.course.id:
                return JsonResponse({'success': True})

        if section.students.count() < 25:
            section.students.add(student)
            return JsonResponse({'success': True})
        else:
            return JsonResponse({'success': False, 'message': 'section is full'})
    return JsonResponse({'success': False, 'message': 'wrong method'})


def log_out(request):
    del request.session['sid']
    return JsonResponse({'success': True})

sections/views.py
from django import urls
from django.shortcuts import render, redirect
from section import views


def to_main(request):
    return redirect('/sections/')

section/templates/section/all_courses.html
<!DOCTYPE html>
{% load static from staticfiles %}
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/all_courses.css' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
<script>
    function reg(s){
        var url = "http://localhost:8000/sections/register?id=" + s;
        $.ajax({
            type: "GET",
            url:url,
            success:function(){

            }
        });
    }
</script>

{% spaceless %}

<div class="container">
    {% for name in names %}
    <div class="panel-margin panel-group">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" href="#collapse{{name.0}}">{{name}}</a>
                </h4>
            </div>
            <div id="collapse{{name.0}}" class="panel-collapse collapse">
                <ul class="list-group">
                    <div class="align">
                        {% for section in sections %}
                        {% if section.2 == name %}
                        <li class="list-group-item">
                            {{ section.1 }}
                            <button type="button" class="btn-custom-style btn btn-primary" onclick="reg({{ section.0 }})"> Register
                            </button>
                        </li>
                        {% endif %}
                        {% endfor %}
                    </div>
                </ul>
            </div>

        </div>
    </div>
    {% endfor %}

</div>
{% endspaceless %}


</body>
</html>

section/templates/section/all_sections.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block imports %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'css/all_courses.css' %}">
<script src="{% static 'js/json.js' %}"></script>
{% endblock %}


{% block content %}
{% spaceless %}

<div class="container">
    <div>
        <button type="button" class="btn btn-primary" onclick="logout()">Logout</button>
        <a href="{% url 'section:sections' %}"><button type="button" class="btn btn-primary pull-right">my sections</button></a>
    </div>
    {% for name in names %}
    <div class="panel-margin panel-group">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" href="#collapse{{name.0}}">{{name}}</a>
                </h4>
            </div>
            <div id="collapse{{name.0}}" class="panel-collapse collapse">
                <ul class="list-group">
                    <div class="align">
                        {% for section in sections %}
                        {% if section.1 == name %}
                        <li class="list-group-item">
                            {{ section.0 }}
                            <button type="button" class="btn-custom-style btn btn-primary"
                                    onclick="reg({{ section.2 }})"> Register
                            </button>
                        </li>
                        {% endif %}
                        {% endfor %}
                    </div>
                </ul>
            </div>

        </div>
    </div>
    {% endfor %}
</div>
{% endspaceless %}
{% endblock %}

section/templates/section/login.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load bootstrap3 %}

{% block title %}
login
{% endblock %}

{% block imports %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/signup.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <span class="glyphicon glyphicon-lock"></span> Login
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="post">
                        {{ form.as_p }}
                        {% csrf_token %}
                        <button type="submit" class="btn btn-success btn-sm">
                            Sign in
                        </button>
                    </form>
                </div>
                <div class="panel-footer">
                    Not Registred? <a href="{% url 'section:signup' %}">Register here</a>
                </div>

            </div>

        </div>
    </div>
</div>
{% endblock %}

section/templates/section/sections.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block imports %}
<script src="{% static 'js/json.js' %}"></script>
{% endblock %}


{% block content %}
{% spaceless %}
<div class="container">
    <div >
        <button type="button" class="btn btn-primary" onclick="logout()">Logout</button>
        <a href="{% url 'section:all_sections' %}">
            <button type="button" class="btn btn-primary pull-right">All sections</button>
        </a>
    </div>
    <div class="panel-group">
        {% for name in names %}
        <div class="panel panel-default">

            <ul class="list-group">
                {% for section in sections %}
                {% if section.1 == name %}
                <li class="list-group-item">{{section.0}} - {{ section.1 }}</li>
                {% endif %}
                {% endfor %}
            </ul>
            <div class="panel-footer">{{ name }}</div>
        </div>
        {% endfor %}
    </div>
</div>
{% endspaceless %}
{% endblock %}

section/templates/section/signup.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load bootstrap3 %}

{% block title %}
sign up
{% endblock %}

{% block imports %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/signup.css' %}">
{% endblock %}



{% block content %}
{% spaceless %}
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <span class="glyphicon glyphicon-lock"></span> Signup
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="post">

                        {{ form.as_p }}
                        {% csrf_token %}

                        <button type="submit" class="btn btn-success btn-sm">
                            Sign up
                        </button>

                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'section:login' %}">Login here</a>
                </div>
            </div>

        </div>
    </div>
</div>
{% endspaceless %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static from staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% block imports %} {% endblock %}
</head>
<body>
{% block content %} {% endblock %}
</body>
</html>